name: Build Framework

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4  # 更新到 v4 版本，解决 Node.js 版本警告

    - name: Select Xcode 13
      run: |
        sudo xcode-select -s /Applications/Xcode_13.4.1.app

    - name: Build Framework
      run: |
        xcodebuild archive \
          -scheme WidgetClockHandRotationEffect \
          -destination "generic/platform=iOS" \
          -archivePath "build/ios.xcarchive" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

        xcodebuild archive \
          -scheme WidgetClockHandRotationEffect \
          -destination "generic/platform=iOS Simulator" \
          -archivePath "build/ios-simulator.xcarchive" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

    - name: Create XCFramework
      run: |
        xcodebuild -create-xcframework \
          -framework build/ios.xcarchive/Products/Library/Frameworks/WidgetClockHandRotationEffect.framework \
          -debug-symbols "$(pwd)/build/ios.xcarchive/dSYMs/WidgetClockHandRotationEffect.framework.dSYM" \
          -framework build/ios-simulator.xcarchive/Products/Library/Frameworks/WidgetClockHandRotationEffect.framework \
          -debug-symbols "$(pwd)/build/ios-simulator.xcarchive/dSYMs/WidgetClockHandRotationEffect.framework.dSYM" \
          -output build/WidgetClockHandRotationEffect.xcframework

    - name: Upload Framework
      uses: actions/upload-artifact@v3
      with:
        name: WidgetClockHandRotationEffect
        path: build/WidgetClockHandRotationEffect.xcframework
